window.myApp.currentJSON = JSON.stringify(
{
  "_settings": {
    "aboutus_execprofile_row_sequence": "2, 4, 3, 4",
    "aboutus_execprofile_0_name": "Linda Li",
    "aboutus_execprofile_0_position": "Co-President",
    "aboutus_execprofile_0_description": "Raised under the sunny skies of California, Linda has found herself calling Boston, Shanghai, and New York home for the last 10 years. After working at McKinsey and the New York City Mayor's Office, she's exploring her passions in economic development, financial technology, and urban policy at HBS and HKS just across the river. Please don't hesitate to say hi whenever you see her!",
    "aboutus_execprofile_0_display": true,
    "aboutus_execprofile_1_display": true,
    "aboutus_execprofile_1_name": "Nonso Maduka",
    "aboutus_execprofile_1_position": "Co-President",
    "aboutus_execprofile_1_description": "Born in Nigeria and raised in Maryland, Nonso has called the East Coast his home for most of his life. He spent his 6 years before HBS navigating the financial crisis at Citigroup. He's passionate about education, technology, and economic policy. He loves meeting people and you can usually spot him hanging out somewhere on the HBS campus so stop him for a conversation if you see him. ",
    "aboutus_execprofile_0_linkedin": "//www.linkedin.com/in/lindali09",
    "aboutus_execprofile_1_linkedin": "//www.linkedin.com/pub/nonso-maduka/55/5a3/387",
    "aboutus_execprofile_2_display": true,
    "aboutus_execprofile_2_name": "Ali Huberlie",
    "aboutus_execprofile_2_position": "Chief Development Officer",
    "aboutus_execprofile_2_description": "After having spent the past six years in Philly and NYC, Ali's move to Boston brought her home to the New England city she loves (she was raised in nearby New Hampshire). She's passionate about education, politics, and fitness, and is rarely found sitting down or standing still. She's thrilled to be a part of the SA this year!",
    "aboutus_execprofile_2_linkedin": "//www.linkedin.com/in/alihuberlie",
    "aboutus_execprofile_3_display": true,
    "aboutus_execprofile_3_name": "Emily Goergen",
    "aboutus_execprofile_3_position": "Chief Marketing Officer",
    "aboutus_execprofile_3_description": "Emily grew up as a cheesehead in Wisconsin, but spent the past decade on the East Coast studying and working in finance.  Beyond her passions for the Green Bay Packers and actual cheese, she's excited about running several new marketing initiatives for the SA this year. If you're creative and would like to help - please reach out to her!",
    "aboutus_execprofile_3_linkedin": "//www.linkedin.com/pub/emily-goergen/21/450/9/",
    "aboutus_execprofile_4_display": true,
    "aboutus_execprofile_4_name": "Sarah Zhang",
    "aboutus_execprofile_4_position": "Chief Development Officer",
    "aboutus_execprofile_4_description": "Sarah was born and raised in Shanghai. Besides attending HBS, she is also pursuing a Master in Public Policy at Harvard Kennedy School. Although not a big fan of long winters, she has enjoyed learning to ski as an adult this year and looks forward to skiing more with friends in the future",
    "aboutus_execprofile_4_linkedin": "//www.linkedin.com/profile/view?id=43916838&trk=nav_responsive_tab_profile",
    "aboutus_execprofile_5_display": true,
    "aboutus_execprofile_5_name": "Lindsay Williams",
    "aboutus_execprofile_5_position": "Chief Events Officer",
    "aboutus_execprofile_5_description": "This past fall, Lindsay left her Midwestern roots (Michigan, Indiana, & Ohio) to venture to Boston (and is one of the few HBSers who absolutely LOVES winter).  Aside from touring manufacturing facilities and analyzing CPG brands, she enjoys traveling, watching college sports, and trying new restaurants with friends.  She would love your opinion on SA events!",
    "aboutus_execprofile_5_linkedin": "//www.linkedin.com/pub/lindsay-williams/20/41b/9b1",
    "aboutus_execprofile_6_display": true,
    "aboutus_execprofile_6_name": "Malavika Srinivasan",
    "aboutus_execprofile_6_description": "Malavika has spent the last many years searching for the coldest places to live (Ohio, Chicago, New York) and she feels right at home walking between HKS and HBS. She loves social enterprise, K-12 education, celebrity gossip, and embarrassing herself on the dance floor. ",
    "aboutus_execprofile_6_position": "Chief Operating Officer",
    "aboutus_execprofile_6_linkedin": "//www.linkedin.com/pub/malavika-srinivasan/9/ba2/448",
    "aboutus_execprofile_7_display": true,
    "aboutus_execprofile_7_name": "Adam Schaack",
    "aboutus_execprofile_7_position": "Head Senator",
    "aboutus_execprofile_7_description": "Adam grew up in Austin and so was unpleasantly surprised by the unfettered snowstorms that accompany Boston winters. Before HBS, Adam worked for Accenture, ExxonMobil, and NASA. He also attended the University of Texas at Austin. When procastinating case reading, Adam is likely to be country western dancing, playing basketball, or losing at poker.",
    "aboutus_execprofile_8_name": "Jeanne Stoll",
    "aboutus_execprofile_8_display": true,
    "aboutus_execprofile_8_position": "Chief Products Officer",
    "aboutus_execprofile_8_description": "Jeanne has bounced around the east coast all her life, growing up in New Jersey, going to college in Maryland, and living in NYC before HBS. When not reading cases, Jeanne enjoys traveling and fulfilling her constant craving for sushi. With the help of the SA's awesome product managers, she's looking forward to bringing you some great HBS swag this year!",
    "aboutus_execprofile_8_linkedin": "//www.linkedin.com/profile/view?id=43331243&trk=nav_responsive_tab_profile",
    "aboutus_execprofile_9_display": true,
    "aboutus_execprofile_9_name": "Heather Silverio",
    "aboutus_execprofile_9_position": "Chief Community Officer",
    "aboutus_execprofile_9_description": "Heather grew up in sunny San Diego and has spent the past few years bouncing between the East and West coasts. Heather loves the great outdoors, crushing cheeseburgers from Tasty Burger and she's the most enthusiastic mediocre sports player this side of the Mississippi.",
    "aboutus_execprofile_9_linkedin": "//www.linkedin.com/in/heathersilverio",
    "aboutus_execprofile_10_display": true,
    "aboutus_execprofile_10_name": "Pato Bichara",
    "aboutus_execprofile_10_position": "Chief Community Officer",
    "aboutus_execprofile_10_description": "Pato grew up in Monterrey, Mexico. He believes in making an impact in Latin America through innovation and entrepreneurship. He is a big fan of weddings and when not singing on a random stage, he can be found on Spangler Lawn planning fun community events with Heather - if you have an idea for an event on campus, please come find them!",
    "aboutus_execprofile_10_linkedin": "//www.linkedin.com/in/patriciobichara",
    "aboutus_execprofile_11_display": true,
    "aboutus_execprofile_11_name": "Paul Kalmbach",
    "aboutus_execprofile_11_position": "Chief Financial Officer",
    "aboutus_execprofile_11_description": "Paul hails from the great state of Ohio, a true buckeye. He has worked in public accounting, manufacturing, politics, and consulting. Being in New England for the past year, Paul has reignited his passion for snow skiing, and also enjoys a good book, backyard sports, and exploring the Boston food scene - any good recommendations let him know.",
    "aboutus_execprofile_11_linkedin": "//www.linkedin.com/in/paulkalmbach/",
    "aboutus_execprofile_12_display": true,
    "aboutus_execprofile_12_name": "Christy Essay",
    "aboutus_execprofile_12_position": "Chief Events Officer",
    "aboutus_execprofile_12_description": "Despite being born and raised in the great state of Texas, Christy has spent the last several years punishing herself with the winters in Minnesota and Indiana.  When not busy planning events of epic proportions, you can find her nurturing her love of retail, watching college football (Go Irish!), or enjoying a glass of wine with friends.",
    "aboutus_execprofile_0_email": "lli@mba2015.hbs.edu",
    "aboutus_execprofile_1_email": "cmaduka@mba2015.hbs.edu",
    "aboutus_execprofile_2_email": "ahuberlie@mba2015.hbs.edu",
    "aboutus_execprofile_3_email": "egoergen@mba2015.hbs.edu",
    "aboutus_execprofile_4_email": "jzhang@mba2015.hbs.edu",
    "aboutus_execprofile_5_email": "lwilliams@mba2015.hbs.edu",
    "aboutus_execprofile_6_email": "msrinivasan@mba2015.hbs.edu",
    "aboutus_execprofile_7_email": "aschaack@mba2015.hbs.edu",
    "aboutus_execprofile_7_linkedin": "//www.linkedin.com/pub/adam-schaack/28/1b9/10a",
    "aboutus_execprofile_8_email": "jstoll@mba2015.hbs.edu",
    "aboutus_execprofile_9_email": "hsilverio@mba2015.hbs.edu",
    "aboutus_execprofile_10_email": "pbichara@mba2015.hbs.edu",
    "aboutus_execprofile_11_email": "pkalmbach@mba2015.hbs.edu",
    "aboutus_execprofile_12_email": "cessay@mba2015.hbs.edu",
    "aboutus_execprofile_0_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/execProfile_linda_li.png?696",
    "aboutus_execprofile_1_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_nonso_maduka.jpg?696",
    "aboutus_execprofile_3_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_emily_goergen.png?696",
    "aboutus_execprofile_4_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_sarah_zhang.jpg?696",
    "aboutus_execprofile_5_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_lindsay_williams.png?696",
    "aboutus_execprofile_6_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_malavika_srinivasan.png?696",
    "aboutus_execprofile_7_picture_link": "https://cdn.shopify.com/s/files/1/0554/7965/files/profile_schaack_adam.png?1134",
    "aboutus_execprofile_8_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_jeanne_stoll.png?696",
    "aboutus_execprofile_9_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_heather_silverio.png?696",
    "aboutus_execprofile_10_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_patricio_bichara.jpg?696",
    "aboutus_execprofile_11_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_paul_kalmbach.jpg?696",
    "aboutus_execprofile_12_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/icon.png?696",
    "aboutus_execprofile_2_picture_link": "https://cdn.shopify.com/s/files/1/0554/7965/files/exec_profile_ali_huberlie.jpg?996"
  },
  "_data": {
    "aboutus_execprofile_row_sequence": "2, 4, 3, 4",
    "aboutus_execprofile_0_name": "Linda Li",
    "aboutus_execprofile_0_position": "Co-President",
    "aboutus_execprofile_0_description": "Raised under the sunny skies of California, Linda has found herself calling Boston, Shanghai, and New York home for the last 10 years. She's passionate about financial technology and politics, and is easily spotted shuttling across the Charles between HKS and HBS.",
    "aboutus_execprofile_0_display": true,
    "aboutus_execprofile_1_display": true,
    "aboutus_execprofile_1_name": "Nonso Maduka",
    "aboutus_execprofile_1_position": "Co-President",
    "aboutus_execprofile_1_description": "Born in Nigeria and raised in Maryland, Nonso has called the East Coast his home for most of his life. He spent his 6 years before HBS navigating the financial crisis at Citigroup. He's passionate about education, technology, and economic policy. He loves meeting people and you can usually spot him hanging out somewhere on the HBS campus so stop him for a conversation if you see him. ",
    "aboutus_execprofile_0_linkedin": "//www.linkedin.com/in/lindali09",
    "aboutus_execprofile_1_linkedin": "//www.linkedin.com/pub/nonso-maduka/55/5a3/387",
    "aboutus_execprofile_2_display": true,
    "aboutus_execprofile_2_name": "Ali Huberlie",
    "aboutus_execprofile_2_position": "Chief Development Officer",
    "aboutus_execprofile_2_description": "After having spent the past six years in Philly and NYC, Ali's move to Boston brought her home to the New England city she loves (she was raised in nearby New Hampshire). She's passionate about education, politics, and fitness, and is rarely found sitting down or standing still. She's thrilled to be a part of the SA this year!",
    "aboutus_execprofile_2_linkedin": "//www.linkedin.com/in/alihuberlie",
    "aboutus_execprofile_3_display": true,
    "aboutus_execprofile_3_name": "Emily Goergen",
    "aboutus_execprofile_3_position": "Chief Marketing Officer",
    "aboutus_execprofile_3_description": "Emily grew up as a cheesehead in Wisconsin, but spent the past decade on the East Coast studying and working in finance.  Beyond her passions for the Green Bay Packers and actual cheese, she's excited about running several new marketing initiatives for the SA this year. If you're creative and would like to help - please reach out to her!",
    "aboutus_execprofile_3_linkedin": "//www.linkedin.com/pub/emily-goergen/21/450/9/",
    "aboutus_execprofile_4_display": true,
    "aboutus_execprofile_4_name": "Sarah Zhang",
    "aboutus_execprofile_4_position": "Chief Development Officer",
    "aboutus_execprofile_4_description": "Sarah was born and raised in Shanghai. Besides attending HBS, she is also pursuing a Master in Public Policy at Harvard Kennedy School. Although not a big fan of long winters, she has enjoyed learning to ski as an adult this year and looks forward to skiing more with friends in the future",
    "aboutus_execprofile_4_linkedin": "//www.linkedin.com/profile/view?id=43916838&trk=nav_responsive_tab_profile",
    "aboutus_execprofile_5_display": true,
    "aboutus_execprofile_5_name": "Lindsay Williams",
    "aboutus_execprofile_5_position": "Chief Events Officer",
    "aboutus_execprofile_5_description": "This past fall, Lindsay left her Midwestern roots (Michigan, Indiana, & Ohio) to venture to Boston (and is one of the few HBSers who absolutely LOVES winter).  Aside from touring manufacturing facilities and analyzing CPG brands, she enjoys traveling, watching college sports, and trying new restaurants with friends.  She would love your opinion on SA events!",
    "aboutus_execprofile_5_linkedin": "//www.linkedin.com/pub/lindsay-williams/20/41b/9b1",
    "aboutus_execprofile_6_display": true,
    "aboutus_execprofile_6_name": "Malavika Srinivasan",
    "aboutus_execprofile_6_description": "Malavika has spent the last many years searching for the coldest places to live (Ohio, Chicago, New York) and she feels right at home walking between HKS and HBS. She loves social enterprise, K-12 education, celebrity gossip, and embarrassing herself on the dance floor. ",
    "aboutus_execprofile_6_position": "Chief Operating Officer",
    "aboutus_execprofile_6_linkedin": "//www.linkedin.com/pub/malavika-srinivasan/9/ba2/448",
    "aboutus_execprofile_7_display": true,
    "aboutus_execprofile_7_name": "Adam Schaack",
    "aboutus_execprofile_7_position": "Head Senator",
    "aboutus_execprofile_7_description": "Adam grew up in Austin and so was unpleasantly surprised by the unfettered snowstorms that accompany Boston winters. Before HBS, Adam worked for Accenture, ExxonMobil, and NASA. He also attended the University of Texas at Austin. When procastinating case reading, Adam is likely to be country western dancing, playing basketball, or losing at poker.",
    "aboutus_execprofile_8_name": "Jeanne Stoll",
    "aboutus_execprofile_8_display": true,
    "aboutus_execprofile_8_position": "Chief Products Officer",
    "aboutus_execprofile_8_description": "Jeanne has bounced around the east coast all her life, growing up in New Jersey, going to college in Maryland, and living in NYC before HBS. When not reading cases, Jeanne enjoys traveling and fulfilling her constant craving for sushi. With the help of the SA's awesome product managers, she's looking forward to bringing you some great HBS swag this year!",
    "aboutus_execprofile_8_linkedin": "//www.linkedin.com/profile/view?id=43331243&trk=nav_responsive_tab_profile",
    "aboutus_execprofile_9_display": true,
    "aboutus_execprofile_9_name": "Heather Silverio",
    "aboutus_execprofile_9_position": "Chief Community Officer",
    "aboutus_execprofile_9_description": "Heather grew up in sunny San Diego and has spent the past few years bouncing between the East and West coasts. Heather loves the great outdoors, crushing cheeseburgers from Tasty Burger and she's the most enthusiastic mediocre sports player this side of the Mississippi.",
    "aboutus_execprofile_9_linkedin": "//www.linkedin.com/in/heathersilverio",
    "aboutus_execprofile_10_display": true,
    "aboutus_execprofile_10_name": "Pato Bichara",
    "aboutus_execprofile_10_position": "Chief Community Officer",
    "aboutus_execprofile_10_description": "Pato grew up in Monterrey, Mexico. He believes in making an impact in Latin America through innovation and entrepreneurship. He is a big fan of weddings and when not singing on a random stage, he can be found on Spangler Lawn planning fun community events with Heather - if you have an idea for an event on campus, please come find them!",
    "aboutus_execprofile_10_linkedin": "//www.linkedin.com/in/patriciobichara",
    "aboutus_execprofile_11_display": true,
    "aboutus_execprofile_11_name": "Paul Kalmbach",
    "aboutus_execprofile_11_position": "Chief Financial Officer",
    "aboutus_execprofile_11_description": "Paul hails from the great state of Ohio, a true buckeye. He has worked in public accounting, manufacturing, politics, and consulting. Being in New England for the past year, Paul has reignited his passion for snow skiing, and also enjoys a good book, backyard sports, and exploring the Boston food scene - any good recommendations let him know.",
    "aboutus_execprofile_11_linkedin": "//www.linkedin.com/in/paulkalmbach/",
    "aboutus_execprofile_12_display": true,
    "aboutus_execprofile_12_name": "Christy Essay",
    "aboutus_execprofile_12_position": "Chief Events Officer",
    "aboutus_execprofile_12_description": "Despite being born and raised in the great state of Texas, Christy has spent the last several years punishing herself with the winters in Minnesota and Indiana.  When not busy planning events of epic proportions, you can find her nurturing her love of retail, watching college football (Go Irish!), or enjoying a glass of wine with friends.",
    "aboutus_execprofile_0_email": "lli@mba2015.hbs.edu",
    "aboutus_execprofile_1_email": "cmaduka@mba2015.hbs.edu",
    "aboutus_execprofile_2_email": "ahuberlie@mba2015.hbs.edu",
    "aboutus_execprofile_3_email": "egoergen@mba2015.hbs.edu",
    "aboutus_execprofile_4_email": "jzhang@mba2015.hbs.edu",
    "aboutus_execprofile_5_email": "lwilliams@mba2015.hbs.edu",
    "aboutus_execprofile_6_email": "msrinivasan@mba2015.hbs.edu",
    "aboutus_execprofile_7_email": "aschaack@mba2015.hbs.edu",
    "aboutus_execprofile_7_linkedin": "",
    "aboutus_execprofile_8_email": "jstoll@mba2015.hbs.edu",
    "aboutus_execprofile_9_email": "hsilverio@mba2015.hbs.edu",
    "aboutus_execprofile_10_email": "pbichara@mba2015.hbs.edu",
    "aboutus_execprofile_11_email": "pkalmbach@mba2015.hbs.edu",
    "aboutus_execprofile_12_email": "cessay@mba2015.hbs.edu"
  }
}
);
