window.myApp.currentJSON = JSON.stringify( 
{
  "_settings": {
    
  },
  "_data": {
    "eventspage_0_display": true,
    "eventspage_0_title": "Casino Night",
    "eventspage_0_date": "8/30/2014",
    "eventspage_0_location": "Westin Waterfront",
    "eventspage_0_description": "Kick-off RC year with some drinks, appetizers, and Casino games!",
    "eventspage_1_display": true,
    "eventspage_1_title": "Halloween Party",
    "eventspage_1_date": "10/30/2014",
    "eventspage_1_location": "TBD",
    "eventspage_1_description": "Dress up in costumes for Halloween and being half-way done with the semester!",
    "eventspage_2_display": true,
    "eventspage_2_title": "Harvard-Yale Game",
    "eventspage_2_date": "11/21/2014",
    "eventspage_2_location": "Harvard Football Stadium",
    "eventspage_2_description": "Come celebrate the second-oldest rivalry in college football as Harvard takes on Yale on our home turf!",
    "eventspage_3_display": true,
    "eventspage_3_title": "Holidazzle",
    "eventspage_3_date": "12/5/2014",
    "eventspage_3_location": "Westin Copley",
    "eventspage_3_description": "Dinner, dancing, open bar, and a live band to wrap up your first semester at HBS!",
    "eventspage_4_display": true,
    "eventspage_4_title": "Newport Ball",
    "eventspage_4_date": "4/25/2015",
    "eventspage_4_location": "Newport, RI",
    "eventspage_4_description": "Start Newport weekend with a glamorous ball at the beautiful Ocean Cliff Manor!",
    "eventspage_5_display": true,
    "eventspage_5_cohort": "EC",
    "eventspage_5_title": "Welcome Back Party",
    "eventspage_5_date": "9/9/2014",
    "eventspage_5_location": "NE Aquarium",
    "eventspage_5_description": "Drinks, dancing, and catching up with your friends to kick off a great EC year!",
    "eventspage_6_display": true,
    "eventspage_6_cohort": "EC",
    "eventspage_6_title": "Halloween Party",
    "eventspage_6_date": "10/30/2014",
    "eventspage_6_location": "TBD",
    "eventspage_6_description": "Dress up in costumes for Halloween and being half-way done with the semester!",
    "eventspage_7_cohort": "EC",
    "eventspage_7_display": true,
    "eventspage_7_title": "Harvard-Yale Game",
    "eventspage_7_date": "11/21/2014",
    "eventspage_7_location": "Harvard Football Stadium",
    "eventspage_7_description": "Come celebrate the second-oldest rivalry in college football as Harvard takes on Yale on our home turf!",
    "eventspage_8_display": true,
    "eventspage_8_cohort": "EC",
    "eventspage_8_title": "Holidazzle",
    "eventspage_8_date": "12/5/2014",
    "eventspage_8_location": "Westin Copley",
    "eventspage_8_description": "Dancing, open bar, a live band, and reconnecting with all your friends before the Holidays!",
    "eventspage_9_display": true,
    "eventspage_9_cohort": "EC",
    "eventspage_9_title": "Ski Trip",
    "eventspage_9_date": "2/26-3/1, 2015",
    "eventspage_9_location": "Breckenridge, CO",
    "eventspage_9_location_link": "",
    "eventspage_9_description": "Hit the slopes in Breckenridge with a weekend full of skiing, parties, and enjoying your friends in the beautiful Colorado air!",
    "eventspage_10_display": true,
    "eventspage_10_cohort": "EC",
    "eventspage_10_title": "EC Gala",
    "eventspage_10_date": "4/10/2015",
    "eventspage_10_location": "Top of the Hub",
    "eventspage_10_description": "The final formal event of your HBS career - hard to believe, but celebrating with great friends with spectacular views of Boston is the best way to do it!",
    "eventspage_11_display": true,
    "eventspage_11_cohort": "EC",
    "eventspage_11_title": "Commencement",
    "eventspage_11_date": "5/28/2015",
    "eventspage_11_location": "HBS",
    "eventspage_0_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_1_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_2_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_3_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_4_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_5_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_6_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_7_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_8_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_9_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_10_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696",
    "eventspage_11_picture_link": "//cdn.shopify.com/s/files/1/0554/7965/files/pictureComingSoon.gif?696"
  }
}
);
