window.myData = {
    "id": 365603947,
    "title": "Patagonia Synchilla Vest: Women's",
    "handle": "patagonia-synchilla-vest-womens-2015",
    "description": "<meta charset=\"utf-8\" />\r\n<p>=note=</p>\r\n<p>For class of 2015, please visit the <a href=\"http://hbs-sa-products.myshopify.com/products/patagonia-synchilla-vest-womens-2015\">1st page</a></p>\r\n<p>For class of 2016, please visit the <a href=\"http://hbs-sa-products.myshopify.com/products/patagonia-synchilla-vest-womens-2016\">2nd page</a></p>",
    "published_at": "2014-09-23T10:40:51-04:00",
    "created_at": "2014-09-23T10:40:52-04:00",
    "vendor": "HBS",
    "type": "Fleece",
    "tags": [
        "all",
        "apparel",
        "fleece",
        "forsale",
        "vest",
        "women"
    ],
    "price": 8900,
    "price_min": 8900,
    "price_max": 8900,
    "available": true,
    "price_varies": false,
    "compare_at_price": null,
    "compare_at_price_min": 0,
    "compare_at_price_max": 0,
    "compare_at_price_varies": false,
    "variants": [
        {
            "id": 857080387,
            "title": "xs / A / Class of 2015",
            "options": [
                "xs",
                "A",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "A",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-0",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080391,
            "title": "xs / B / Class of 2015",
            "options": [
                "xs",
                "B",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "B",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-1",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080395,
            "title": "xs / C / Class of 2015",
            "options": [
                "xs",
                "C",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "C",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-2",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080399,
            "title": "xs / D / Class of 2015",
            "options": [
                "xs",
                "D",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "D",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-3",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080403,
            "title": "xs / E / Class of 2015",
            "options": [
                "xs",
                "E",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "E",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-4",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080407,
            "title": "xs / F / Class of 2015",
            "options": [
                "xs",
                "F",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "F",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-5",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080411,
            "title": "xs / G / Class of 2015",
            "options": [
                "xs",
                "G",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "G",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-6",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080415,
            "title": "xs / H / Class of 2015",
            "options": [
                "xs",
                "H",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "H",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-7",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080419,
            "title": "xs / I / Class of 2015",
            "options": [
                "xs",
                "I",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "I",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-8",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080423,
            "title": "xs / J / Class of 2015",
            "options": [
                "xs",
                "J",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "J",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-9",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080427,
            "title": "sm / A / Class of 2015",
            "options": [
                "sm",
                "A",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "A",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-10",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080431,
            "title": "sm / B / Class of 2015",
            "options": [
                "sm",
                "B",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "B",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-11",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080435,
            "title": "sm / C / Class of 2015",
            "options": [
                "sm",
                "C",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "C",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-12",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080439,
            "title": "sm / D / Class of 2015",
            "options": [
                "sm",
                "D",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "D",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-13",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080447,
            "title": "sm / E / Class of 2015",
            "options": [
                "sm",
                "E",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "E",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-14",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080451,
            "title": "sm / F / Class of 2015",
            "options": [
                "sm",
                "F",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "F",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-15",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080455,
            "title": "sm / G / Class of 2015",
            "options": [
                "sm",
                "G",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "G",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-16",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080459,
            "title": "sm / H / Class of 2015",
            "options": [
                "sm",
                "H",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "H",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-17",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080463,
            "title": "sm / I / Class of 2015",
            "options": [
                "sm",
                "I",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "I",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-18",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080467,
            "title": "sm / J / Class of 2015",
            "options": [
                "sm",
                "J",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "J",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-19",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080471,
            "title": "md / A / Class of 2015",
            "options": [
                "md",
                "A",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "A",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-20",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080475,
            "title": "md / B / Class of 2015",
            "options": [
                "md",
                "B",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "B",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-21",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080479,
            "title": "md / C / Class of 2015",
            "options": [
                "md",
                "C",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "C",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-22",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080483,
            "title": "md / D / Class of 2015",
            "options": [
                "md",
                "D",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "D",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-23",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080487,
            "title": "md / E / Class of 2015",
            "options": [
                "md",
                "E",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "E",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-24",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080495,
            "title": "md / F / Class of 2015",
            "options": [
                "md",
                "F",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "F",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-25",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080499,
            "title": "md / G / Class of 2015",
            "options": [
                "md",
                "G",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "G",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-26",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080503,
            "title": "md / H / Class of 2015",
            "options": [
                "md",
                "H",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "H",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-27",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080507,
            "title": "md / I / Class of 2015",
            "options": [
                "md",
                "I",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "I",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-28",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080511,
            "title": "md / J / Class of 2015",
            "options": [
                "md",
                "J",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "J",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-29",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080515,
            "title": "lg / A / Class of 2015",
            "options": [
                "lg",
                "A",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "A",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-30",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080519,
            "title": "lg / B / Class of 2015",
            "options": [
                "lg",
                "B",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "B",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-31",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080523,
            "title": "lg / C / Class of 2015",
            "options": [
                "lg",
                "C",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "C",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-32",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080527,
            "title": "lg / D / Class of 2015",
            "options": [
                "lg",
                "D",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "D",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-33",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080531,
            "title": "lg / E / Class of 2015",
            "options": [
                "lg",
                "E",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "E",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-34",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080535,
            "title": "lg / F / Class of 2015",
            "options": [
                "lg",
                "F",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "F",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-35",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080539,
            "title": "lg / G / Class of 2015",
            "options": [
                "lg",
                "G",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "G",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-36",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080543,
            "title": "lg / H / Class of 2015",
            "options": [
                "lg",
                "H",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "H",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-37",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080547,
            "title": "lg / I / Class of 2015",
            "options": [
                "lg",
                "I",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "I",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-38",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080551,
            "title": "lg / J / Class of 2015",
            "options": [
                "lg",
                "J",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "J",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-39",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080555,
            "title": "xl / A / Class of 2015",
            "options": [
                "xl",
                "A",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "A",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-40",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080559,
            "title": "xl / B / Class of 2015",
            "options": [
                "xl",
                "B",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "B",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-41",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080563,
            "title": "xl / C / Class of 2015",
            "options": [
                "xl",
                "C",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "C",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-42",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080567,
            "title": "xl / D / Class of 2015",
            "options": [
                "xl",
                "D",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "D",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-43",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080571,
            "title": "xl / E / Class of 2015",
            "options": [
                "xl",
                "E",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "E",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-44",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080575,
            "title": "xl / F / Class of 2015",
            "options": [
                "xl",
                "F",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "F",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-45",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080579,
            "title": "xl / G / Class of 2015",
            "options": [
                "xl",
                "G",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "G",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-46",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080583,
            "title": "xl / H / Class of 2015",
            "options": [
                "xl",
                "H",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "H",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-47",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080587,
            "title": "xl / I / Class of 2015",
            "options": [
                "xl",
                "I",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "I",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-48",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080591,
            "title": "xl / J / Class of 2015",
            "options": [
                "xl",
                "J",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "J",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-49",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080595,
            "title": "xs / no section / Partner",
            "options": [
                "xs",
                "no section",
                "Partner"
            ],
            "option1": "xs",
            "option2": "no section",
            "option3": "Partner",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-50",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080599,
            "title": "sm / no section / Partner",
            "options": [
                "sm",
                "no section",
                "Partner"
            ],
            "option1": "sm",
            "option2": "no section",
            "option3": "Partner",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-51",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080607,
            "title": "md / no section / Partner",
            "options": [
                "md",
                "no section",
                "Partner"
            ],
            "option1": "md",
            "option2": "no section",
            "option3": "Partner",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-52",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080611,
            "title": "lg / no section / Partner",
            "options": [
                "lg",
                "no section",
                "Partner"
            ],
            "option1": "lg",
            "option2": "no section",
            "option3": "Partner",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-53",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080619,
            "title": "xl / no section / Partner",
            "options": [
                "xl",
                "no section",
                "Partner"
            ],
            "option1": "xl",
            "option2": "no section",
            "option3": "Partner",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-54",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080627,
            "title": "xs / no section / Parent",
            "options": [
                "xs",
                "no section",
                "Parent"
            ],
            "option1": "xs",
            "option2": "no section",
            "option3": "Parent",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-55",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080631,
            "title": "sm / no section / Parent",
            "options": [
                "sm",
                "no section",
                "Parent"
            ],
            "option1": "sm",
            "option2": "no section",
            "option3": "Parent",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-56",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080635,
            "title": "md / no section / Parent",
            "options": [
                "md",
                "no section",
                "Parent"
            ],
            "option1": "md",
            "option2": "no section",
            "option3": "Parent",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-57",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080639,
            "title": "lg / no section / Parent",
            "options": [
                "lg",
                "no section",
                "Parent"
            ],
            "option1": "lg",
            "option2": "no section",
            "option3": "Parent",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-58",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080643,
            "title": "xl / no section / Parent",
            "options": [
                "xl",
                "no section",
                "Parent"
            ],
            "option1": "xl",
            "option2": "no section",
            "option3": "Parent",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-59",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080647,
            "title": "xs / no section / Class of 2015",
            "options": [
                "xs",
                "no section",
                "Class of 2015"
            ],
            "option1": "xs",
            "option2": "no section",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-60",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080651,
            "title": "sm / no section / Class of 2015",
            "options": [
                "sm",
                "no section",
                "Class of 2015"
            ],
            "option1": "sm",
            "option2": "no section",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-61",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080655,
            "title": "md / no section / Class of 2015",
            "options": [
                "md",
                "no section",
                "Class of 2015"
            ],
            "option1": "md",
            "option2": "no section",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-62",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080659,
            "title": "lg / no section / Class of 2015",
            "options": [
                "lg",
                "no section",
                "Class of 2015"
            ],
            "option1": "lg",
            "option2": "no section",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-63",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080663,
            "title": "xl / no section / Class of 2015",
            "options": [
                "xl",
                "no section",
                "Class of 2015"
            ],
            "option1": "xl",
            "option2": "no section",
            "option3": "Class of 2015",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-64",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080671,
            "title": "xs / no section / Crest Only",
            "options": [
                "xs",
                "no section",
                "Crest Only"
            ],
            "option1": "xs",
            "option2": "no section",
            "option3": "Crest Only",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-65",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080675,
            "title": "sm / no section / Crest Only",
            "options": [
                "sm",
                "no section",
                "Crest Only"
            ],
            "option1": "sm",
            "option2": "no section",
            "option3": "Crest Only",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-66",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080679,
            "title": "md / no section / Crest Only",
            "options": [
                "md",
                "no section",
                "Crest Only"
            ],
            "option1": "md",
            "option2": "no section",
            "option3": "Crest Only",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-67",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080683,
            "title": "lg / no section / Crest Only",
            "options": [
                "lg",
                "no section",
                "Crest Only"
            ],
            "option1": "lg",
            "option2": "no section",
            "option3": "Crest Only",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-68",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        },
        {
            "id": 857080687,
            "title": "xl / no section / Crest Only",
            "options": [
                "xl",
                "no section",
                "Crest Only"
            ],
            "option1": "xl",
            "option2": "no section",
            "option3": "Crest Only",
            "price": 8900,
            "weight": 0,
            "compare_at_price": null,
            "inventory_quantity": 1,
            "inventory_management": null,
            "inventory_policy": "deny",
            "available": true,
            "sku": "fleece-2015-vest-w-69",
            "requires_shipping": true,
            "taxable": true,
            "barcode": null,
            "featured_image": null
        }
    ],
    "images": [
        "//cdn.shopify.com/s/files/1/0595/0661/products/pictureComingSoon_fbaf8081-9744-4f1a-ad04-fa4847a37030.gif?v=1411483253"
    ],
    "featured_image": "//cdn.shopify.com/s/files/1/0595/0661/products/pictureComingSoon_fbaf8081-9744-4f1a-ad04-fa4847a37030.gif?v=1411483253",
    "options": [
        {
            "name": "Size",
            "position": 1
        },
        {
            "name": "Section",
            "position": 2
        },
        {
            "name": "Design",
            "position": 3
        }
    ],
    "url": "/products/patagonia-synchilla-vest-womens-2015"
};